name: Meltano - Hub Metrics Publish

on:
  schedule:
    - cron:  '0 6 * * thu'

  workflow_dispatch:

jobs:
  hub_metrics_publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data/
    environment: production
    env:
      MELTANO_ENVIRONMENT: prod
      MELTANO_SEND_ANONYMOUS_USAGE_STATS: 'false'
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      TAP_SNOWFLAKE_METRICS_TABLES: '["MELTANO_HUB.FACT_VARIANT_HUB_METRICS"]'
      TAP_SNOWFLAKE_AUDIT_TABLES: '["MELTANO_HUB.HUB_METRICS_AUDIT"]'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: '3.8'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run: echo "${{secrets.MELTANO_ENV_FILE }}" > .env
    # Install Plugins
    - run: meltano install --schedule=hub_metrics_publish
    # Run Test
    - run: meltano run hub_metrics_publish
