name: Prod Deploy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  dbt_seed:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data/
    environment: production
    env:
      MELTANO_ENVIRONMENT: prod
      MELTANO_SEND_ANONYMOUS_USAGE_STATS: 'false'
      CI_BRANCH: 'b${{ github.SHA }}'
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'
    # Add SSH key for accessing private dbt package repo
    - uses: webfactory/ssh-agent@v0.7.0
      with:
          ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
    - run: pip install -r requirements.txt
    # Seed Production
    - run: meltano install utility dbt-snowflake
    - run: meltano run dbt-snowflake:run_dbt_artifacts
    - run: meltano invoke dbt-snowflake seed --full-refresh
