name: Meltano - Slack Publish

on:
  schedule:
    - cron:  '0 12 * * *'

  workflow_dispatch:

jobs:
  slack_notifications:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data/
    environment: production
    env:
      MELTANO_ENVIRONMENT: prod
      MELTANO_SEND_ANONYMOUS_USAGE_STATS: 'false'
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      TAP_SNOWFLAKE_SINGER_ACTIVITY: '["MELTANO_HUB.SINGER_ACTIVITY_NOTIFICATIONS"]'
      TAP_SNOWFLAKE_MELTANO_ACTIVITY: '["MELTANO_HUB.MELTANO_ACTIVITY_NOTIFICATIONS"]'
      TARGET_APPRISE_SINGER_ACTIVITY_URIS: ${{ secrets.TARGET_APPRISE_SINGER_ACTIVITY_URIS }}
      TARGET_APPRISE_MELTANO_ACTIVITY_URIS: ${{ secrets.TARGET_APPRISE_MELTANO_ACTIVITY_URIS }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run: echo "${{secrets.MELTANO_ENV_FILE }}" > .env
    # Install Plugins
    - run: meltano install --schedule=slack_notifications
    # Run Test
    - run: meltano run slack_notifications